<?php

namespace App\Http\Controllers;

use App\BlogPost;
use Illuminate\Http\Request;
use App\Http\Requests\StorePost;
use App\Image;
// use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use App\User;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')
            ->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // difference b/w lazy loading and eager loading
        // DB::connection()->enableQueryLog();
        // $posts = BlogPost::with('comments')->get();
        // foreach ($posts as $post) {
        //     foreach ($post->comments as $comment) {
        //         echo $comment->content;
        //     }
        // }
        // dd(DB::getQueryLog());

        // comments_count
        return view('posts.index', 
                [
                    'posts' => BlogPost::latestWithRelations()->get(),
                ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        //dd(BlogPost::find($id));
        // $request->session()->reflash();
        
        // return view('posts.show', ['post' => BlogPost::with(['comments' => function($builder) {
        //     return $builder->latest();
        // }])->findOrFail($id)]);

        $counter = 0;

        return view('posts.show', 
            [
                'post' => BlogPost::with('comments', 'tags', 'user', 'comments.user')->findOrFail($id),
                'counter' => $counter,
            ]);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(StorePost $request)
    {
        $validatedData = $request->validated();
        $validatedData['user_id'] = $request->user()->id;

        $blogPost = BlogPost::create($validatedData);
        // $blogPost = new BlogPost();
        // $blogPost->title = $request->input('title');
        // $blogPost->content = $request->input('content');
        // $blogPost->save();

        $hasFile = $request->hasFile('thumbnail');
        if ($hasFile)
        {
            $file = $request->file('thumbnail');

            // $file->store('thumbnails');
            // Storage::disk('public')->putFile('thumbnails', $file);

            $path = $file->storeAs('thumbnails', $blogPost->id . '.' . $file->guessExtension());
            // Storage::putFileAs('thumbnails', $file, $blogPost->id . '.' . $file->guessExtension());

            // dump(Storage::url($path)); // storage folder in public folder link is generated by "php artisan storage:link"

            $blogPost->image()->save(
                Image::create(['path' => $path])
            );
        }

        $request->session()->flash('status', 'Blog post was created!');

        // return redirect()->route('posts.index');
        return redirect()->route('posts.show', ['post' => $blogPost->id]);
    }

    public function edit($id)
    {
        $post = BlogPost::findOrFail($id);

        // if (Gate::denies('update-post', $post)) 
        // {
        //     abort(403, 'You cannot edit this blog post!');
        // }
        $this->authorize('update', $post);
        
        return view('posts.edit', ['post' => $post]);
    }

    public function update(StorePost $request, $id)
    {
        $post = BlogPost::findOrFail($id);

        // if (Gate::denies('update-post', $post)) 
        // {
        //     abort(403, 'You cannot edit this blog post!');
        // }
        $this->authorize('update', $post);

        $validatedData = $request->validated();
        
        $post->fill($validatedData);

        if ($request->hasFile('thumbnail'))
        {
            $file = $request->file('thumbnail');
            $path = $file->storeAs('thumbnails', $post->id . '.' . $file->guessExtension());

            if ($post->image)
            {
                Storage::delete($post->image->path);
                $post->image->path = $path;
                $post->image->save();
            }
            else
            {
                $post->image()->save(
                    Image::create(['path' => $path])
                );
            }
        }

        $post->save();
        $request->session()->flash('status', 'Blog post was updated!');
        return redirect()->route('posts.show', ['post' => $post->id]);
    }

    public function destroy(Request $request, $id)
    {
        $post = BlogPost::findOrFail($id);

        // if (Gate::denies('delete-post', $post)) 
        // {
        //     abort(403, 'You cannot delete this blog post!');
        // }
        $this->authorize('delete', $post);

        $post->delete();

        //BlogPost::destroy($id);

        $request->session()->flash('status', 'Blog post was deleted!');
        return redirect()->route('posts.index');
    }
}
